name: Generate Client Code

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-python-client:
    runs-on: ubuntu-latest
    name: Generate client code from OpenAPI document
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Python Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          openapi-file: api.yaml
          generator: python
          command-args: --package-name quanta_client

      - name: Package the generated client
        run: |
          # Create a zip file from the generated-client directory
          zip -r quanta-client.zip python-client

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload generated client as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./quanta-client.zip
          asset_name: quanta-client.zip
          asset_content_type: application/zip
